//LOGIN ACTION TYPES
export const LOGIN = "LOGIN";
export const LOGIN_GOOGLE = "LOGIN_GOOGLE"
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; 
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';