//LOGIN 
export const LOGIN = "LOGIN"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
//LOGIN GOOGLE
export const LOGIN_GOOGLE = "LOGIN_GOOGLE" 
export const LOGIN_GOOGLE_ERROR = "LOGIN_GOOGLE_ERROR"
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS'
//LOG OUT
export const LOG_OUT = 'LOG_OUT'
//REGISTER
export const REGISTER = 'REGISTER'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
//GET LIBROS
export const GET_LIBROS = "GET_LIBROS"
export const GET_LIBROS_ERROR = "GET_LIBROS_ERROR"
export const GET_LIBROS_SUCCESS = "GET_LIBROS_SUCCESS"
//DELETE LIBROS
export const DELETE_LIBROS = "DELETE_LIBROS"
export const DELETE_LIBROS_ERROR = "DELETE_LIBROS_ERROR"
export const DELETE_LIBROS_SUCCESS = "DELETE_LIBROS_SUCCESS"
//UPDATE LIBROS
export const UPDATE_LIBROS = "UPDATE_LIBROS"
export const UPDATE_LIBROS_ERROR = "UPDATE_LIBROS_ERROR"
export const UPDATE_LIBROS_SUCCESS = "UPDATE_LIBROS_SUCCESS"
//POST LIBROS
export const POST_LIBROS = "POST_LIBROS"
export const POST_LIBROS_ERROR = "POST_LIBROS_ERROR"
export const POST_LIBROS_SUCCESS = "POST_LIBROS_SUCCESS"
//GET PERSONA
export const GET_PERSONA = "GET_PERSONA"
export const GET_PERSONA_ERROR = "GET_PERSONA_ERROR"
export const GET_PERSONA_SUCCESS = "GET_PERSONA_SUCCESS"
//GET CATEGORIAS
export const GET_CATEGORIAS = "GET_CATEGORIAS"
export const GET_CATEGORIAS_ERROR = "GET_CATEGORIAS_ERROR"
export const GET_CATEGORIAS_SUCCESS = "GET_CATEGORIAS_SUCCESS"
//POST CATEGORIAS
export const POST_CATEGORIAS = "POST_CATEGORIAS"
export const POST_CATEGORIAS_ERROR = "POST_CATEGORIAS_ERROR"
export const POST_CATEGORIAS_SUCCESS = "POST_CATEGORIAS_SUCCESS"
//DELETE CATEGORIAS
export const DELETE_CATEGORIAS = "DELETE_CATEGORIAS"
export const DELETE_CATEGORIAS_ERROR = "DELETE_CATEGORIAS_ERROR"
export const DELETE_CATEGORIAS_SUCCESS = "DELETE_CATEGORIAS_SUCCESS"
//TOAST
export const TOAST = "TOAST"
export const RELOAD = "RELOAD"
export const LOADED = "LOADED"